export const siteUrl = "https://softbridge-solutions.sites.openai.com";

export type PageData = { slug: string; title: string; eyebrow: string; description: string; intro: string; short?: string; code?: string; type?: string; sections: { title: string; body: string; bullets?: string[] }[]; faq: { q: string; a: string }[] };

const faqBase = (topic: string) => [
  { q: `How does Softbridge Solutions approach ${topic}?`, a: `We begin with the operating problem, the available evidence and the consequences of error. Architecture follows from those constraints. Prototypes are evaluated with representative tasks before a production path is selected.` },
  { q: `Can ${topic} connect to existing enterprise systems?`, a: `Yes, when appropriate. Integration design typically considers identity, permissions, data boundaries, APIs, event systems and human review. The exact path depends on the organization’s current architecture.` },
  { q: `How is quality measured?`, a: `Quality should be defined at task level. We use representative evaluation sets, explicit success and failure criteria, traces, operational feedback and cost measures relevant to the work being completed.` },
];

export const primarySolutions: PageData[] = [
  { slug: "ai-agents", title: "AI Agents", eyebrow: "Agentic systems", short: "Bounded systems that reason, use tools and complete multi-step work with oversight.", description: "Design and engineering of production AI agents with tools, memory, evaluation, observability and human control.", intro: "An AI agent is a software system that uses a model to interpret a goal, choose actions and interact with tools or information. In enterprise settings, useful autonomy is bounded: permissions, state, escalation and evaluation matter as much as the model.", sections: [
    { title: "What makes an agent production-ready", body: "A production agent needs a defined task boundary, controlled access to tools, durable state where necessary, recovery paths and clear ownership. The design should make both successful and failed actions inspectable.", bullets: ["Tool and API orchestration", "Retrieval and working memory", "Human approval at consequential steps", "Tracing, evaluation and incident learning"] },
    { title: "Single agents and multi-agent systems", body: "A single agent is often the clearest design. Multiple specialized agents become useful when roles have genuinely different context, tools or evaluation criteria. Additional agents create coordination cost, so the architecture must earn its complexity." },
    { title: "Common enterprise use cases", body: "Agents can support research synthesis, service operations, document workflows, internal knowledge access, sales operations and software delivery. The best candidates combine repeatable steps, accessible systems and a clear definition of completion." },
  ], faq: faqBase("AI agents") },
  { slug: "enterprise-ai", title: "Enterprise AI", eyebrow: "Organization-wide systems", short: "AI architecture that connects strategy, governance, software and measurable operations.", description: "Enterprise AI strategy and engineering grounded in business workflows, governance, security and measurable operational outcomes.", intro: "Enterprise AI is the coordinated use of machine intelligence across an organization’s processes, products and decisions. It is broader than adopting a model: it includes data, applications, integration, governance, operating ownership and measurement.", sections: [
    { title: "From opportunity portfolio to operating system", body: "A strong program distinguishes experiments from capabilities worth operating. Opportunities can be prioritized by value, feasibility, risk and the quality of available feedback—not novelty alone.", bullets: ["Workflow and decision mapping", "Architecture and build-versus-buy choices", "Governance proportional to risk", "Capability transfer to internal teams"] },
    { title: "Architecture principles", body: "Enterprise architectures should preserve choice across models, keep sensitive data within intentional boundaries and expose quality and cost. Shared platform components are valuable when they reduce duplicated work without obscuring accountability." },
    { title: "Responsible adoption", body: "Controls work best when they are part of delivery. Access, evaluation, review, logging and change management should be mapped to each system’s actual use and impact." },
  ], faq: faqBase("enterprise AI") },
  { slug: "generative-ai", title: "Generative AI", eyebrow: "Grounded generation", short: "Generative systems that work with enterprise knowledge, rules and quality controls.", description: "Generative AI applications grounded in enterprise context, with retrieval, evaluation, safeguards and clear operating measures.", intro: "Generative AI creates or transforms text, code, images and other content from learned patterns. In business systems, value depends on grounding generation in trustworthy context and matching outputs to a defined task.", sections: [
    { title: "Where generation adds value", body: "Useful applications compress reading, drafting and synthesis while preserving expert review where judgment matters. Good candidates have abundant source material, repeatable output expectations and fast feedback.", bullets: ["Knowledge assistants and semantic search", "Document drafting and transformation", "Analyst and developer copilots", "Multilingual service operations"] },
    { title: "Grounding and retrieval", body: "Retrieval-augmented generation can provide current, permission-aware evidence to a model. Chunking, metadata, ranking and citation design affect performance; a vector database alone does not guarantee useful retrieval." },
    { title: "Evaluation before release", body: "Evaluation should test factual support, completeness, format, safety and usefulness with representative inputs. Model-as-judge techniques can assist, but calibrated human review remains important." },
  ], faq: faqBase("generative AI") },
  { slug: "llm-development", title: "LLM Development", eyebrow: "Language-model applications", short: "Model selection, RAG, fine-tuning and evaluation for reliable language systems.", description: "Large language model application development, including RAG, model routing, fine-tuning, evaluation and observability.", intro: "LLM development is the engineering of applications around large language models. The work includes context design, retrieval, tools, structured outputs, evaluation, security, latency and cost—not prompt writing in isolation.", sections: [
    { title: "Choosing the adaptation method", body: "Prompting, retrieval and fine-tuning solve different problems. Prompting shapes behavior, retrieval supplies changing knowledge, and fine-tuning can improve consistent task behavior when sufficient high-quality examples exist.", bullets: ["Model and provider evaluation", "Retrieval-augmented generation", "Structured outputs and tool calling", "Fine-tuning data and evaluation design"] },
    { title: "Model routing and infrastructure", body: "Different tasks may warrant different models. Routing can balance capability, latency, location and cost, provided the application retains consistent contracts and observable decisions." },
    { title: "Security for language systems", body: "Threat modeling should cover prompt injection, data leakage, excessive tool permissions and unsafe output handling. Defenses belong at multiple layers rather than in a single system prompt." },
  ], faq: faqBase("LLM applications") },
  { slug: "workflow-automation", title: "Workflow Automation", eyebrow: "Human + machine operations", short: "Automation that connects models to the systems and decisions where work happens.", description: "AI-enabled workflow automation for document, knowledge and operational processes, designed with controls and human oversight.", intro: "Workflow automation coordinates repeatable work across people and systems. AI extends conventional rules-based automation to ambiguous inputs such as documents, messages and requests—but uncertainty must remain visible.", sections: [
    { title: "What to automate", body: "The right starting point is a stable workflow with meaningful volume, accessible inputs and a clear owner. Steps can be classified as deterministic, model-assisted or judgment-led.", bullets: ["Process and exception mapping", "Document and message understanding", "System and API integration", "Queues, approvals and escalation"] },
    { title: "Human-in-the-loop by design", body: "Human review is not a failure of automation. It is an architectural control that can be placed according to confidence, impact and reversibility, then reduced as evidence improves." },
    { title: "Measuring operational value", body: "Cycle time, rework, exception rate, quality and expert attention are usually more useful than a headline automation percentage. Measures should connect directly to the operating outcome." },
  ], faq: faqBase("workflow automation") },
];

const capability = (slug:string,title:string,eyebrow:string,description:string,intro:string,sections:string[]):PageData => ({slug,title,eyebrow,description,intro,sections:sections.map((x,i)=>({title:["Core approach","Production considerations","Where it fits"][i],body:x})),faq:faqBase(title)});

export const additionalSolutions = [
  capability("machine-learning","Machine Learning","Predictive systems","Machine learning systems for prediction, classification, recommendation and decision support.","Machine learning uses data to learn patterns that support predictions or decisions. Effective systems depend on problem formulation, representative data and feedback loops as much as algorithms.",["We frame the target, available signals and acceptable error before comparing baselines and model families. Simpler approaches remain valuable when they are easier to operate and explain.","Data drift, label quality, feature pipelines and monitoring determine long-term reliability. Production ownership includes retraining and rollback decisions.","Applications include demand signals, risk prioritization, classification, recommendations and anomaly detection where historical evidence is meaningful."]),
  capability("computer-vision","Computer Vision","Visual intelligence","Computer vision systems for inspection, classification, extraction and visual workflow support.","Computer vision enables software to interpret images and video. Enterprise use requires careful attention to capture conditions, edge cases, privacy and the operational decision that follows a prediction.",["We assess imaging conditions and annotation quality, establish a baseline and test performance across meaningful slices of the environment.","Deployment may involve cloud, edge or hybrid inference. Latency, device limits, privacy and model updates shape the design.","Use cases include quality inspection, document understanding, asset monitoring and visual search where image evidence changes a workflow."]),
  capability("natural-language-processing","Natural Language Processing","Language intelligence","NLP systems for classification, extraction, search and multilingual enterprise workflows.","Natural language processing covers methods that allow software to analyze and generate human language. Modern systems combine classical methods, embeddings and large language models according to the task.",["Tasks are defined at the level of intent, entities, relationships, retrieval or generation. Domain language and multilingual variation must be represented in evaluation data.","Structured schemas, confidence handling and provenance help language outputs interact safely with downstream software.","NLP supports message routing, contract and document analysis, semantic search, knowledge extraction and service operations."]),
];

export const industries = [
  { slug:"financial-services", title:"Financial services", focus:"Knowledge, operations and controlled decision support" },
  { slug:"healthcare", title:"Healthcare", focus:"Administrative workflows and responsible information access" },
  { slug:"manufacturing", title:"Manufacturing", focus:"Visual inspection, maintenance and operational knowledge" },
  { slug:"retail", title:"Retail", focus:"Demand, service and product intelligence" },
  { slug:"professional-services", title:"Professional services", focus:"Research, documents and expert productivity" },
  { slug:"technology", title:"Technology", focus:"AI-native products and software delivery" },
];

export const resourcePages: PageData[] = [
  capability("engineering-blog","Engineering Blog","Build notes","Technical articles about building and operating AI systems.","The Engineering Blog is Softbridge Solutions’ home for practical notes on architecture, evaluation, integration and operations. Publication items will identify authors, dates, updates and methods.",["Articles prioritize reproducible explanations, design trade-offs and implementation detail.","Future posts will include diagrams, references and code where they improve understanding.","Browse related research, benchmarks and open-source work as each collection grows."]),
  capability("ai-research","AI Research","Research program","Applied research on reliable, useful and governable AI systems.","Softbridge Solutions’ applied research program focuses on the questions that determine whether AI systems remain useful in real operating conditions.",["Priority themes include agent evaluation, grounded generation, human oversight and cost-aware orchestration.","Research pages will distinguish hypotheses, methods, evidence, limitations and implications.","Verified papers and collaborations will be listed here when available; no unverified claims are presented."]),
  capability("whitepapers","Whitepapers","Long-form analysis","Methodical long-form guides for enterprise AI decisions.","Whitepapers turn complex AI engineering decisions into structured, referenceable guidance for technical and operational leaders.",["Each paper will state its scope, intended reader, method, publication date and revision history.","Topics will connect strategic choices to architecture and operational consequences.","Downloads will be added when reviewed publications are available."]),
  capability("benchmarks","Benchmarks","Evaluation evidence","Transparent benchmarks for models, retrieval and agent systems.","Benchmarks should help teams make a decision, not produce a decorative leaderboard. This collection will document tasks, datasets, rubrics, environments and limitations.",["Task sets should resemble the intended workflow and expose meaningful failure modes.","Results require enough context to understand variance, cost and measurement choices.","Verified benchmark reports will be published here as they become available."]),
  capability("datasets","Datasets","Data resources","Documented datasets for evaluation and applied AI research.","A useful dataset includes provenance, scope, intended use, known limitations and responsible access conditions—not files alone.",["Dataset cards will describe collection and preparation methods.","Licensing, privacy and sensitive attributes must be explicit.","This page is a transparent placeholder until reviewed datasets are released."]),
  capability("open-source","Open Source","Shared tools","Open tools and reference implementations for practical AI engineering.","Open source can make methods inspectable and reusable. Future Softbridge Solutions releases will be linked here with documentation, ownership and licensing.",["Projects should solve a clear engineering problem and include maintainable examples.","Security policy, contribution guidance and release history will accompany active projects.","No repositories are claimed until they are verified and publicly available."]),
];
resourcePages.forEach((x,i)=>{x.code=["E/01","R/02","W/03","B/04","D/05","O/06"][i];x.type=["Engineering","Research","Analysis","Evaluation","Data","Code"][i]});

const companyPages = [
  capability("about","About Softbridge","Company","About Softbridge Solutions, a Lisbon-based AI engineering and software company.","Softbridge Solutions is an AI engineering company based in Lisbon, Portugal. We work at the intersection of artificial intelligence, enterprise software and workflow design.",["Our purpose is to turn advances in models into dependable systems that improve real work.","We value clear problem definitions, evidence, responsible control and software that can be operated over time.","Verified legal, address and company-registration details should be added before broad public launch."]),
  capability("our-mission","Our Mission","Company direction","The mission guiding Softbridge Solutions’ AI engineering work.","Our mission is to help organizations make artificial intelligence useful, understandable and accountable in the work that matters.",["We connect emerging capability to concrete operating needs.","We design systems people can inspect, guide and improve.","We share practical knowledge that helps the wider field make better decisions."]),
  capability("our-vision","Our Vision","Company direction","The long-term vision for human-centered enterprise AI.","We envision organizations where AI expands human capacity without obscuring responsibility: systems handle repeatable complexity while people retain authority over consequential judgment.",["Models will change quickly; durable architecture must preserve choice.","Trust grows from evidence, transparency and appropriate control.","Lisbon can be an important bridge between European research, talent and responsible application."]),
  capability("leadership","Leadership","People","Leadership and expert authorship at Softbridge Solutions.","Leadership details are intentionally awaiting verification. This page is structured to provide biographies, areas of responsibility, professional history and authored work once approved.",["Named profiles should use verified titles, experience and professional links.","Every research or engineering publication should identify its accountable author.","Do not infer team members, credentials, clients or awards from incomplete information."]),
  capability("engineering","Engineering","How we build","Softbridge Solutions’ principles for engineering dependable AI systems.","We treat AI as a software and operations discipline. Models are components inside systems with data contracts, interfaces, permissions, evaluation, observability and owners.",["Prefer the smallest architecture that satisfies the evidence.","Design for model change, uncertain outputs and recoverable failure.","Make quality, cost, latency and human intervention visible in operation."]),
  capability("research","Research","Applied inquiry","Applied AI research and evaluation at Softbridge Solutions.","Our research direction centers on reliable agents, grounded generation, evaluation and the interaction between people and AI systems.",["Research claims must be supported by disclosed methods and limits.","Applied work should connect a technical question to an operating consequence.","Publications will include dates, authorship, references and revision notes when released."]),
  capability("products","Products","Software","AI products and software applications from Softbridge Solutions.","This is the future home of verified Softbridge Solutions products. Product claims, availability and pricing will be published only when confirmed.",["Each product page will define the user, problem, system behavior and important limitations.","SoftwareApplication and Product structured data will be added only for real, available offerings.","Explore current solution capabilities while the product portfolio is prepared."]),
  capability("case-studies","Case Studies","Applied work","Evidence-led case studies for enterprise AI systems.","Case studies will document the problem, constraints, method, system and measured outcome of verified work. No customer names or performance claims are presented without approval.",["Strong case studies separate starting conditions from intervention and result.","Measures should explain time period, definition and limitations.","Anonymized studies may be used when confidentiality permits and context remains useful."]),
  capability("press","Press","Newsroom","Verified announcements and media resources from Softbridge Solutions.","This newsroom will contain verified company announcements, media references and approved brand resources.",["Every release will include a publication date and contact owner.","Historical corrections and material updates should remain visible.","Press contact details are pending verification."]),
  capability("events","Events","Community","Events, technical sessions and public appearances from Softbridge Solutions.","Confirmed talks, workshops and community events will be listed here with dates, venues, speakers and access details.",["Event entries must distinguish organizer, host and participant roles.","Recordings and materials can extend the usefulness of completed events.","No upcoming events are claimed at this time."]),
  capability("careers","Careers","Join the team","Career opportunities at a Lisbon-based AI engineering company.","Softbridge Solutions is building an environment for careful, curious people who want to turn AI capability into dependable software. Open roles will appear here only when verified.",["Role pages should state outcomes, responsibilities, location and hiring process clearly.","We value systems thinking, evidence and direct communication.","No open positions are claimed at this time; speculative applications can use the contact page."]),
  capability("faq","Frequently Asked Questions","Reference","Answers about Softbridge Solutions, enterprise AI engagements and responsible delivery.","This page answers common questions about who Softbridge Solutions is, what we build and how we approach enterprise AI work.",["Softbridge Solutions is based in Lisbon, Portugal and focuses on AI engineering and enterprise software.","Engagement scope begins with the workflow, constraints and evidence—not a predetermined model.","Company-specific legal and contact details will be published once verified."]),
  capability("contact","Contact","Start a conversation","Contact Softbridge Solutions about enterprise AI engineering in Lisbon.","Bring us a workflow, decision or product where AI may create measurable value. A useful first note describes the current process, users, systems and consequence of getting it wrong.",["Share the operating problem and who owns it.","Describe available data, systems and important constraints.","Verified direct email, telephone and office-address details are pending publication."]),
  capability("ai-solutions","AI Solutions","Capabilities","Explore Softbridge Solutions’ AI agents, enterprise AI, generative AI, LLM and automation capabilities.","Our capabilities connect models to enterprise context. Each area is approached as part of a complete system: data, software, workflow, evaluation and human control.",["Explore agents, enterprise AI, generative AI, language-model development and workflow automation.","Supporting capabilities include machine learning, computer vision and natural language processing.","The right architecture follows from the task, operating environment and evidence."]),
  capability("industries","Industries","Operating contexts","AI systems for financial services, healthcare, manufacturing, retail, professional services and technology.","Industry context changes what a useful and responsible AI system looks like. Language, processes, data, risk and integration patterns must be understood before design decisions are made.",["We learn the workflow and its exceptions with domain experts.","Controls are mapped to the consequences and reversibility of decisions.","Industry pages provide use cases and design considerations, not unsupported outcome claims."]),
  capability("resources","Resources","Knowledge center","Engineering articles, AI research, whitepapers, benchmarks, datasets and open-source resources.","The Softbridge Solutions knowledge center organizes practical AI engineering content for human readers and machine retrieval. Each collection is built for clear provenance and future depth.",["Content clusters connect concepts, implementations, evidence and related systems.","Pages use clear authorship, publication and revision metadata when items are available.","Explore engineering, research, whitepapers, benchmarks, datasets and open source."]),
];

const industryPages:PageData[] = industries.map(x=>capability(`industries/${x.slug}`,x.title,"Industry context",`AI engineering considerations and use cases for ${x.title.toLowerCase()}.`,`AI in ${x.title.toLowerCase()} should be designed around sector language, workflows, evidence and consequences. Softbridge Solutions approaches the domain from Lisbon with European operating context in mind.`,[
  `Potential applications include ${x.focus.toLowerCase()}. Candidate workflows require validation with domain owners before implementation.`,
  "Privacy, security, recordkeeping, human review and applicable regulation must be mapped to the specific system and jurisdiction.",
  "A first engagement should establish the workflow baseline, representative cases and measurable definition of improvement.",
]));

export const pages: PageData[] = [...primarySolutions, ...additionalSolutions, ...resourcePages, ...companyPages, ...industryPages];
export const pageMap = new Map(pages.map(x=>[x.slug,x]));
