const configuredSiteUrl =
  process.env.NEXT_PUBLIC_SITE_URL ??
  process.env.VERCEL_PROJECT_PRODUCTION_URL ??
  "http://localhost:3000";

export const siteUrl = configuredSiteUrl.startsWith("http")
  ? configuredSiteUrl
  : `https://${configuredSiteUrl}`;

export type PageData = { slug: string; title: string; eyebrow: string; description: string; intro: string; short?: string; code?: string; type?: string; sections: { title: string; body: string; bullets?: string[] }[]; faq: { q: string; a: string }[]; sources?: { label: string; url: string }[] };

const faqBase = (topic: string) => [
  { q: `How does Softbridge Solutions approach ${topic}?`, a: `We begin with the operating problem, the available evidence and the consequences of error. Architecture follows from those constraints. Prototypes are evaluated with representative tasks before a production path is selected.` },
  { q: `Can ${topic} connect to existing enterprise systems?`, a: `Yes, when appropriate. Integration design typically considers identity, permissions, data boundaries, APIs, event systems and human review. The exact path depends on the organization’s current architecture.` },
  { q: `How is quality measured?`, a: `Quality should be defined at task level. We use representative evaluation sets, explicit success and failure criteria, traces, operational feedback and cost measures relevant to the work being completed.` },
];

export const primarySolutions: PageData[] = [
  { slug: "ai-agents", title: "AI Agents", eyebrow: "Agentic systems", short: "Bounded systems that reason, use tools and complete multi-step work with oversight.", description: "Design and engineering of production AI agents with tools, memory, evaluation, observability and human control.", intro: "An AI agent is a software system that uses a model to interpret a goal, choose actions and interact with tools or information. In enterprise settings, useful autonomy is bounded: permissions, state, escalation and evaluation matter as much as the model.", sections: [
    { title: "What makes an agent production-ready", body: "A production agent needs a defined task boundary, controlled access to tools, durable state where necessary, recovery paths and clear ownership. The design should make both successful and failed actions inspectable.", bullets: ["Tool and API orchestration", "Retrieval and working memory", "Human approval at consequential steps", "Tracing, evaluation and incident learning"] },
    { title: "Single agents and multi-agent systems", body: "A single agent is often the clearest design. Multiple specialized agents become useful when roles have genuinely different context, tools or evaluation criteria. Additional agents create coordination cost, so the architecture must earn its complexity." },
    { title: "Common enterprise use cases", body: "Agents can support research synthesis, service operations, document workflows, internal knowledge access, sales operations and software delivery. The best candidates combine repeatable steps, accessible systems and a clear definition of completion." },
  ], faq: faqBase("AI agents") },
  { slug: "enterprise-ai", title: "Enterprise AI", eyebrow: "Organization-wide systems", short: "AI architecture that connects strategy, governance, software and measurable operations.", description: "Enterprise AI strategy and engineering grounded in business workflows, governance, security and measurable operational outcomes.", intro: "Enterprise AI is the coordinated use of machine intelligence across an organization’s processes, products and decisions. It is broader than adopting a model: it includes data, applications, integration, governance, operating ownership and measurement.", sections: [
    { title: "From opportunity portfolio to operating system", body: "A strong program distinguishes experiments from capabilities worth operating. Opportunities can be prioritized by value, feasibility, risk and the quality of available feedback—not novelty alone.", bullets: ["Workflow and decision mapping", "Architecture and build-versus-buy choices", "Governance proportional to risk", "Capability transfer to internal teams"] },
    { title: "Architecture principles", body: "Enterprise architectures should preserve choice across models, keep sensitive data within intentional boundaries and expose quality and cost. Shared platform components are valuable when they reduce duplicated work without obscuring accountability." },
    { title: "Responsible adoption", body: "Controls work best when they are part of delivery. Access, evaluation, review, logging and change management should be mapped to each system’s actual use and impact." },
  ], faq: faqBase("enterprise AI") },
  { slug: "generative-ai", title: "Generative AI", eyebrow: "Grounded generation", short: "Generative systems that work with enterprise knowledge, rules and quality controls.", description: "Generative AI applications grounded in enterprise context, with retrieval, evaluation, safeguards and clear operating measures.", intro: "Generative AI creates or transforms text, code, images and other content from learned patterns. In business systems, value depends on grounding generation in trustworthy context and matching outputs to a defined task.", sections: [
    { title: "Where generation adds value", body: "Useful applications compress reading, drafting and synthesis while preserving expert review where judgment matters. Good candidates have abundant source material, repeatable output expectations and fast feedback.", bullets: ["Knowledge assistants and semantic search", "Document drafting and transformation", "Analyst and developer copilots", "Multilingual service operations"] },
    { title: "Grounding and retrieval", body: "Retrieval-augmented generation can provide current, permission-aware evidence to a model. Chunking, metadata, ranking and citation design affect performance; a vector database alone does not guarantee useful retrieval." },
    { title: "Evaluation before release", body: "Evaluation should test factual support, completeness, format, safety and usefulness with representative inputs. Model-as-judge techniques can assist, but calibrated human review remains important." },
  ], faq: faqBase("generative AI") },
  { slug: "llm-development", title: "LLM Development", eyebrow: "Language-model applications", short: "Model selection, RAG, fine-tuning and evaluation for reliable language systems.", description: "Large language model application development, including RAG, model routing, fine-tuning, evaluation and observability.", intro: "LLM development is the engineering of applications around large language models. The work includes context design, retrieval, tools, structured outputs, evaluation, security, latency and cost—not prompt writing in isolation.", sections: [
    { title: "Choosing the adaptation method", body: "Prompting, retrieval and fine-tuning solve different problems. Prompting shapes behavior, retrieval supplies changing knowledge, and fine-tuning can improve consistent task behavior when sufficient high-quality examples exist.", bullets: ["Model and provider evaluation", "Retrieval-augmented generation", "Structured outputs and tool calling", "Fine-tuning data and evaluation design"] },
    { title: "Model routing and infrastructure", body: "Different tasks may warrant different models. Routing can balance capability, latency, location and cost, provided the application retains consistent contracts and observable decisions." },
    { title: "Security for language systems", body: "Threat modeling should cover prompt injection, data leakage, excessive tool permissions and unsafe output handling. Defenses belong at multiple layers rather than in a single system prompt." },
  ], faq: faqBase("LLM applications") },
  { slug: "workflow-automation", title: "Workflow Automation", eyebrow: "Human + machine operations", short: "Automation that connects models to the systems and decisions where work happens.", description: "AI-enabled workflow automation for document, knowledge and operational processes, designed with controls and human oversight.", intro: "Workflow automation coordinates repeatable work across people and systems. AI extends conventional rules-based automation to ambiguous inputs such as documents, messages and requests—but uncertainty must remain visible.", sections: [
    { title: "What to automate", body: "The right starting point is a stable workflow with meaningful volume, accessible inputs and a clear owner. Steps can be classified as deterministic, model-assisted or judgment-led.", bullets: ["Process and exception mapping", "Document and message understanding", "System and API integration", "Queues, approvals and escalation"] },
    { title: "Human-in-the-loop by design", body: "Human review is not a failure of automation. It is an architectural control that can be placed according to confidence, impact and reversibility, then reduced as evidence improves." },
    { title: "Measuring operational value", body: "Cycle time, rework, exception rate, quality and expert attention are usually more useful than a headline automation percentage. Measures should connect directly to the operating outcome." },
  ], faq: faqBase("workflow automation") },
];

const capability = (slug:string,title:string,eyebrow:string,description:string,intro:string,sections:readonly string[]):PageData => ({slug,title,eyebrow,description,intro,sections:sections.map((x,i)=>({title:["Core approach","Production considerations","Where it fits"][i],body:x})),faq:faqBase(title)});

export const additionalSolutions = [
  capability("machine-learning","Machine Learning","Predictive systems","Machine learning systems for prediction, classification, recommendation and decision support.","Machine learning uses data to learn patterns that support predictions or decisions. Effective systems depend on problem formulation, representative data and feedback loops as much as algorithms.",["We frame the target, available signals and acceptable error before comparing baselines and model families. Simpler approaches remain valuable when they are easier to operate and explain.","Data drift, label quality, feature pipelines and monitoring determine long-term reliability. Production ownership includes retraining and rollback decisions.","Applications include demand signals, risk prioritization, classification, recommendations and anomaly detection where historical evidence is meaningful."]),
  capability("computer-vision","Computer Vision","Visual intelligence","Computer vision systems for inspection, classification, extraction and visual workflow support.","Computer vision enables software to interpret images and video. Enterprise use requires careful attention to capture conditions, edge cases, privacy and the operational decision that follows a prediction.",["We assess imaging conditions and annotation quality, establish a baseline and test performance across meaningful slices of the environment.","Deployment may involve cloud, edge or hybrid inference. Latency, device limits, privacy and model updates shape the design.","Use cases include quality inspection, document understanding, asset monitoring and visual search where image evidence changes a workflow."]),
  capability("natural-language-processing","Natural Language Processing","Language intelligence","NLP systems for classification, extraction, search and multilingual enterprise workflows.","Natural language processing covers methods that allow software to analyze and generate human language. Modern systems combine classical methods, embeddings and large language models according to the task.",["Tasks are defined at the level of intent, entities, relationships, retrieval or generation. Domain language and multilingual variation must be represented in evaluation data.","Structured schemas, confidence handling and provenance help language outputs interact safely with downstream software.","NLP supports message routing, contract and document analysis, semantic search, knowledge extraction and service operations."]),
];

export const industries = [
  { slug:"manufacturing", title:"Manufacturing", focus:"Visual inspection, predictive maintenance and shop-floor knowledge" },
  { slug:"agriculture", title:"Agriculture", focus:"Crop intelligence, forecasting, field operations and decision support" },
  { slug:"logistics", title:"Logistics", focus:"Routing, demand signals, document flow and exception handling" },
  { slug:"healthcare", title:"Healthcare", focus:"Administrative workflows and responsible information access" },
  { slug:"retail", title:"Retail", focus:"Demand, service and product intelligence" },
  { slug:"education", title:"Education", focus:"Learning support, institutional knowledge and responsible assistants" },
  { slug:"smart-cities", title:"Smart cities", focus:"Urban operations, citizen services and infrastructure intelligence" },
  { slug:"financial-services", title:"Financial services", focus:"Knowledge, operations and controlled decision support" },
  { slug:"professional-services", title:"Professional services", focus:"Research, documents and expert productivity" },
  { slug:"technology", title:"Technology", focus:"AI-native products and software delivery" },
];

export const resourcePages: PageData[] = [
  capability("engineering-blog","Engineering Blog","Build notes","Technical articles about building and operating AI systems.","The Engineering Blog is Softbridge Solutions’ home for practical notes on architecture, evaluation, integration and operations. Publication items will identify authors, dates, updates and methods.",["Articles prioritize reproducible explanations, design trade-offs and implementation detail.","Future posts will include diagrams, references and code where they improve understanding.","Browse related research, benchmarks and open-source work as each collection grows."]),
  capability("ai-research","AI Research","Research program","Applied research on reliable, useful and governable AI systems.","Softbridge Solutions’ applied research program focuses on the questions that determine whether AI systems remain useful in real operating conditions.",["Priority themes include agent evaluation, grounded generation, human oversight and cost-aware orchestration.","Research pages will distinguish hypotheses, methods, evidence, limitations and implications.","Verified papers and collaborations will be listed here when available; no unverified claims are presented."]),
  capability("research-papers","Research Papers","Research library","A structured library for reviewed AI research notes, papers and technical references.","Research papers should make evidence easier to inspect. This page organizes future Softbridge Solutions papers and selected technical references around methods, limits and practical consequences.",["A useful paper page should identify the question, method, dataset, assumptions, evaluation criteria and known limits.","Research summaries should connect technical results to architecture decisions, not merely repeat abstracts.","This collection avoids claiming publications until reviewed papers are available."]),
  capability("whitepapers","Whitepapers","Long-form analysis","Methodical long-form guides for enterprise AI decisions.","Whitepapers turn complex AI engineering decisions into structured, referenceable guidance for technical and operational leaders.",["Each paper will state its scope, intended reader, method, publication date and revision history.","Topics will connect strategic choices to architecture and operational consequences.","Downloads will be added when reviewed publications are available."]),
  capability("benchmarks","Benchmarks","Evaluation evidence","Transparent benchmarks for models, retrieval and agent systems.","Benchmarks should help teams make a decision, not produce a decorative leaderboard. This collection will document tasks, datasets, rubrics, environments and limitations.",["Task sets should resemble the intended workflow and expose meaningful failure modes.","Results require enough context to understand variance, cost and measurement choices.","Verified benchmark reports will be published here as they become available."]),
  capability("datasets","Datasets","Data resources","Documented datasets for evaluation and applied AI research.","A useful dataset includes provenance, scope, intended use, known limitations and responsible access conditions—not files alone.",["Dataset cards will describe collection and preparation methods.","Licensing, privacy and sensitive attributes must be explicit.","This page is a transparent placeholder until reviewed datasets are released."]),
  capability("open-source","Open Source","Shared tools","Open tools and reference implementations for practical AI engineering.","Open source can make methods inspectable and reusable. Future Softbridge Solutions releases will be linked here with documentation, ownership and licensing.",["Projects should solve a clear engineering problem and include maintainable examples.","Security policy, contribution guidance and release history will accompany active projects.","No repositories are claimed until they are verified and publicly available."]),
  capability("documentation","Documentation","Technical docs","Documentation for Softbridge Solutions methods, reference architectures and implementation patterns.","Documentation is where a technical reader should understand how a system behaves, what it depends on and how it is evaluated. This page is structured for future guides, API notes and architecture references.",["Good documentation states prerequisites, inputs, outputs, failure behavior and maintenance expectations.","Architecture notes should include trade-offs, diagrams and operational checks where useful.","No private APIs, products or integrations are claimed until they exist and are approved for publication."]),
];
resourcePages.forEach((x,i)=>{x.code=["E/01","R/02","P/03","W/04","B/05","D/06","O/07","X/08"][i];x.type=["Engineering","Research","Papers","Analysis","Evaluation","Data","Code","Docs"][i]});

const knowledgeTopics = [
  ["artificial-intelligence","Artificial Intelligence","Foundation topic","Artificial intelligence explained as a practical engineering discipline for Adana, Türkiye and global organizations.","Artificial intelligence is the design of systems that can perceive, reason, predict, generate or act with a level of adaptation that conventional software does not provide. For businesses, the important question is not whether a system uses AI, but whether it improves a real workflow with measurable quality and responsible control.",["AI systems can classify information, retrieve knowledge, generate drafts, recommend actions, detect patterns and coordinate work. Each use case requires a clear task definition and evidence that the system improves the current process.","Architecture choices depend on the shape of the problem: rules for stable logic, machine learning for patterns in data, retrieval for knowledge access, language models for flexible reasoning and agents for multi-step work.","Strong AI adoption in Türkiye should connect national ambition, local talent, sector needs and careful governance. Softbridge Solutions uses Adana as its base while writing for a broader technical audience." ]],
  ["large-language-models","Large Language Models","LLM foundations","A technical guide to LLMs, context, prompting, retrieval, evaluation and enterprise use.","Large language models are neural systems trained to predict and generate language-like sequences. They can summarize, transform, reason over context and use tools, but they do not automatically know whether an output is true, complete or safe for a business decision.",["LLM applications need context management, structured outputs, model selection, latency planning and safeguards around tool use. The application layer matters as much as the model choice.","RAG, fine-tuning and prompt engineering are different adaptation methods. Retrieval supplies current evidence, fine-tuning teaches patterns of behavior and prompting shapes the immediate task.","Evaluation should include factual grounding, format compliance, refusal behavior, multilingual performance and cost per useful completed task." ]],
  ["rag","Retrieval-Augmented Generation","Grounded AI","RAG architecture for enterprise knowledge, semantic search and grounded generative AI.","Retrieval-augmented generation connects a language model to external knowledge before it answers. A useful RAG system is not simply a vector database; it is a retrieval, ranking, permissions, citation and evaluation system wrapped around a user workflow.",["Core design choices include chunking, metadata, embedding models, hybrid search, reranking, freshness and source presentation. These choices determine whether the model receives evidence that actually answers the question.","Enterprise RAG must respect identity, access control and data boundaries. A retrieved document should only be visible when the user would be allowed to see it outside the AI system.","Good evaluation tests answer support, missing evidence, conflicting evidence, citation usefulness and behavior when the knowledge base does not contain an answer." ]],
  ["prompt-engineering","Prompt Engineering","Interaction design","Prompt engineering as task design, context design and evaluation design for LLM systems.","Prompt engineering is the craft of giving a model enough task structure, context and output expectations to behave usefully. In production, prompts should be treated as versioned application assets with tests, owners and change history.",["Useful prompts define role, objective, constraints, evidence, output format and failure behavior. They should be short enough to maintain and specific enough to evaluate.","Prompting is not a substitute for retrieval, permissions or workflow design. If the model lacks evidence or can call unsafe tools, prompt text alone cannot make the system reliable.","Patterns include few-shot examples, rubrics, chain-of-thought privacy controls, structured JSON outputs, self-checking and decomposition into smaller steps." ]],
  ["vector-databases","Vector Databases","Semantic infrastructure","Vector databases for embeddings, semantic retrieval and AI application memory.","Vector databases store mathematical representations of text, images or other data so applications can retrieve items by semantic similarity. They are useful for search and RAG, but performance depends on data preparation and ranking strategy.",["A vector index should be designed around the retrieval task, not around storage convenience. Chunk size, overlap, metadata and embedding selection all shape answer quality.","Hybrid retrieval often combines keyword search, vector search and reranking. This can improve recall and precision when domain terminology is specific.","Operational concerns include refresh pipelines, deletion, access control, observability, evaluation sets and cost of embedding updates." ]],
  ["model-context-protocol","Model Context Protocol","Agent interoperability","MCP explained as a pattern for connecting AI applications to external tools and context.","The Model Context Protocol is part of a wider movement toward standardized ways for models and agents to access tools, resources and context. The underlying architectural question is how to expose capability without giving an AI system uncontrolled access.",["Tool interfaces should describe actions, inputs, outputs, permissions and failure modes clearly. The model should not need to guess how a business system behaves.","MCP-style integrations are useful when multiple agents or applications need consistent access to documents, databases, developer tools or operational systems.","Security design should include least privilege, approval gates, audit logs, rate limits and separate handling for read-only and write-capable tools." ]],
  ["cloud-ai","Cloud AI","Deployment models","Cloud AI architecture for scalable model access, data boundaries and operational reliability.","Cloud AI gives teams access to managed models, inference infrastructure, storage and observability. The benefit is speed and scale; the responsibility is understanding where data flows and how the service will behave under load.",["Architecture decisions compare hosted APIs, private deployments, edge inference and hybrid patterns. Each choice affects latency, cost, control and compliance.","Production systems need environment separation, secrets management, monitoring, quota planning and fallback behavior when providers change or fail.","Cloud AI should be measured by reliable completed work, not by the number of experimental services connected to a prototype." ]],
  ["ai-infrastructure","AI Infrastructure","Operating layer","Infrastructure patterns for model serving, retrieval, evaluation, agents and observability.","AI infrastructure is the operating layer that lets models become dependable systems. It includes data pipelines, vector indexes, model gateways, evaluation harnesses, tracing, human review interfaces and deployment workflows.",["Shared infrastructure can reduce duplicated work when teams repeatedly need retrieval, model routing, evaluations or audit trails. It should not hide ownership of individual systems.","Observability should show prompts, retrieved evidence, tool calls, latency, cost, confidence signals and user feedback where appropriate.","The infrastructure must preserve flexibility because models, prices, capabilities and regulations change quickly." ]],
  ["business-automation","Business Automation","Operational systems","Business automation with AI, rules, human review and measurable workflow improvement.","Business automation connects tasks, people and software so work moves with less friction. AI is useful where inputs are ambiguous, documents vary or decisions require synthesis from multiple sources.",["The first step is process mapping: identify stable rules, judgment-heavy steps, exceptions, handoffs and measurable bottlenecks.","Automation should distinguish reversible actions from consequential actions. Human approval belongs where uncertainty or impact is high.","Common patterns include intake triage, document extraction, service routing, knowledge lookup, report drafting and exception queues." ]],
  ["digital-transformation","Digital Transformation","Business change","Digital transformation in Türkiye through software, data, AI and operating discipline.","Digital transformation is not a procurement event. It is the redesign of workflows, data flows and decision rights so an organization can operate with better information and faster feedback.",["AI increases the need for clean process ownership because models amplify both good and bad operational design.","Transformation programs should connect business outcomes, system architecture, adoption, training, measurement and governance.","For Turkish businesses, useful transformation often begins with practical workflows: documents, customer operations, production planning, logistics, finance and internal knowledge." ]],
  ["healthcare-ai","Healthcare AI","Sector guide","Healthcare AI explained for administrative workflows, knowledge access and responsible support.","Healthcare AI must be designed with unusually careful attention to privacy, safety, professional responsibility and local regulation. Many useful applications are administrative or informational rather than clinical decision-making.",["Candidate use cases include document routing, appointment support, coding assistance, internal knowledge access and patient-service operations where expert review remains clear.","Systems should separate administrative help from medical advice and make escalation paths visible.","Evaluation should include completeness, factual support, privacy handling, bias risk and the consequence of incorrect outputs." ]],
  ["manufacturing-ai","Manufacturing AI","Sector guide","Manufacturing AI for inspection, maintenance, planning and operational knowledge.","Manufacturing AI can support quality inspection, anomaly detection, maintenance planning, production knowledge access and supply-chain decisions. The best systems are designed around plant realities, not abstract dashboards.",["Computer vision may detect visible defects when imaging conditions and labels are reliable. Predictive models can prioritize maintenance when historical signals are meaningful.","LLM systems can help operators and engineers search manuals, standard procedures and maintenance history with source-grounded answers.","Adoption should start with a baseline: current defect rates, downtime causes, review times or planning delays, then test AI against representative cases." ]],
  ["retail-ai","Retail AI","Sector guide","Retail AI for demand, product information, service operations and personalization.","Retail AI can improve how teams understand demand, organize product information and answer customer or staff questions. It must respect privacy, brand rules and the operational limits of available data.",["Use cases include product enrichment, semantic search, service triage, demand signals, inventory prioritization and campaign analysis.","Generative systems should be grounded in approved product data and policy so they do not invent availability, pricing or claims.","Evaluation can track answer accuracy, search success, resolution time, rework and human override rate." ]],
  ["logistics-ai","Logistics AI","Sector guide","Logistics AI for routing, document processing, forecasting and exception management.","Logistics work contains many moving parts: documents, locations, schedules, constraints, partners and exceptions. AI can help when systems are connected to reliable operational data and clear decision ownership.",["Potential workflows include shipment document extraction, ETA communication, demand forecasting, routing support and exception prioritization.","Automated suggestions should expose the evidence behind a decision so operators can challenge or override it.","For Adana and Çukurova, logistics content should be written carefully around regional context without unsupported market claims." ]],
  ["agriculture-ai","Agriculture AI","Sector guide","Agriculture AI for crop intelligence, forecasting, planning and field decisions.","Agriculture AI can combine satellite data, field observations, weather signals, sensor data and expert knowledge to support decisions. Useful systems must fit the local crop, season, data quality and human workflow.",["Examples include disease detection support, irrigation planning, yield forecasting, input optimization and knowledge assistants for field teams.","Models should be evaluated across seasons, locations and field conditions because agricultural data changes with environment and practice.","Human expertise remains central: AI should support agronomists, producers and operations teams rather than obscure uncertainty." ]],
  ["education-ai","Education AI","Sector guide","Education AI for learning support, institutional knowledge and responsible assistance.","Education AI can support learners, teachers and institutions when it is designed around pedagogy, privacy and fairness. The goal should be better learning and administration, not novelty.",["Use cases include tutoring support, feedback drafting, curriculum search, institutional knowledge access and student-service triage.","Systems should make limitations clear and avoid replacing professional judgment in sensitive decisions.","Evaluation should include learning usefulness, factual accuracy, accessibility, bias, privacy and student safety." ]],
  ["smart-cities","Smart Cities","Civic technology","Smart city AI for urban operations, service access and infrastructure intelligence.","Smart city systems use data and software to improve urban operations. AI may help summarize requests, prioritize maintenance, detect anomalies and make civic knowledge easier to access.",["Public-sector systems need transparency, accessibility, auditability and careful handling of personal data.","Useful applications often start with service workflows: citizen requests, infrastructure reports, scheduling, document review and operational dashboards.","Any claims about city outcomes should be supported by measured evidence; this page explains design principles rather than promising results." ]],
] as const;

export const knowledgePages: PageData[] = knowledgeTopics.map(([slug,title,eyebrow,description,intro,...rest]) => capability(slug,title,eyebrow,description,intro,rest[0]));

const officialSources = [
  { label: "Republic of Türkiye National AI Strategy portal", url: "https://yapayzekavizyonu.sanayi.gov.tr/" },
  { label: "Çukurova Development Agency", url: "https://www.cka.org.tr/" },
];

export const localPages: PageData[] = [
  { ...capability("adana-ai-ecosystem","AI Ecosystem in Adana","Local authority","An informative guide to Adana’s AI opportunity, technology context and responsible adoption paths.","Adana’s AI ecosystem should be understood through people, universities, software talent, industry needs, public support mechanisms and the wider Çukurova economy. This page avoids unsupported claims and focuses on the practical ingredients that help an AI company operate credibly from Adana.",["A local ecosystem grows when technical talent, applied problems, learning communities and business demand reinforce each other. AI companies can contribute by publishing useful knowledge, training teams and building systems that solve concrete regional problems.","Relevant local opportunities include manufacturing, agriculture, logistics, retail operations, education and public services. Each opportunity should be validated with domain owners before any claim of impact.","Softbridge Solutions positions Adana as its home base while serving organizations that need careful AI engineering, software development and workflow automation." ]), sources: officialSources },
  { ...capability("adana-technology-ecosystem","Adana Technology Ecosystem","Local authority","A practical overview of technology, software and innovation context in Adana and Çukurova.","The Adana technology ecosystem is best described through capabilities and needs: software development, applied engineering, university talent, industrial demand and regional innovation support. Strong content should help readers understand the ecosystem without exaggerating its size or maturity.",["Technology companies in Adana can build authority by solving visible problems, documenting methods and connecting local operating knowledge with global software standards.","Çukurova’s economic context gives AI builders a reason to study manufacturing, logistics, agriculture and service operations closely.","Public agencies and regional development organizations are useful reference points for understanding innovation priorities and support programs." ]), sources: officialSources },
  { ...capability("innovation-in-cukurova","Innovation in Çukurova","Regional context","How AI, software and digital transformation can support innovation in the Çukurova region.","Innovation in Çukurova should connect research, business operations and practical technology adoption. AI becomes valuable when it helps organizations learn faster, reduce friction and make better use of their own knowledge.",["The region’s opportunity is not limited to startups. Established organizations can innovate by digitizing workflows, improving data quality and adopting AI in carefully measured steps.","Useful innovation content should explain concepts, compare options and help leaders ask better questions before investing.","Softbridge Solutions treats regional context as a design input: language, processes, talent, infrastructure and sector priorities affect AI architecture." ]), sources: officialSources },
  { ...capability("software-development-adana","Software Development in Adana","Local authority","A guide to modern software development and AI engineering from Adana, Türkiye.","Software development in Adana can serve local and international needs when it follows strong engineering standards: clear requirements, maintainable architecture, testing, security and operational ownership.",["AI projects still depend on ordinary software excellence. Authentication, data models, user experience, deployment, monitoring and maintainability decide whether a prototype survives real use.","Custom software is valuable when existing tools cannot match a workflow, integration need or data boundary.","A credible Adana-based software company should explain its methods openly and avoid unverifiable claims about clients, awards or scale." ]), sources: officialSources },
  { ...capability("ai-opportunities-turkiye","AI Opportunities in Türkiye","National context","Educational guidance on AI opportunities for businesses and institutions in Türkiye.","Türkiye’s AI opportunity spans enterprise productivity, industry modernization, public services, education, research and software exports. The responsible path is to connect ambition with evidence, skills and governance.",["National AI strategy creates an important reference point for businesses planning adoption, but each organization still needs a workflow-level roadmap.","High-value opportunities often begin in document-heavy operations, knowledge access, manufacturing, logistics, customer service and decision support.","AI adoption should include training, evaluation, cybersecurity, data governance and human accountability from the beginning." ]), sources: officialSources },
  { ...capability("digital-transformation-turkish-businesses","Digital Transformation for Turkish Businesses","Business guide","A practical guide to AI, automation and software modernization for Turkish businesses.","Digital transformation for Turkish businesses should be pragmatic. The strongest starting points are workflows where better data, automation and AI support can reduce rework, improve response time or make expertise easier to access.",["Leaders should map processes before choosing platforms. A poor process wrapped in AI usually becomes a faster poor process.","Implementation should connect business owners, technical teams and end users through measurable pilots and staged rollouts.","Governance should be proportional: stricter controls for higher-impact decisions, lighter controls for reversible productivity tools." ]), sources: officialSources },
  { ...capability("tech-talent-adana","Tech Talent in Adana","Local authority","How Adana can develop AI, software and data talent through practical learning and real projects.","Tech talent grows when people can learn fundamentals, practice on meaningful problems and see a path from education to real engineering work. AI increases the value of strong software, data and product judgment.",["Useful skills include programming, data modeling, statistics, cloud systems, UX, security, evaluation and clear technical writing.","Local companies can help talent by publishing learning material, offering honest project narratives and creating internships or junior roles only when they can support them well.","This page does not claim hiring numbers or university partnerships; it outlines the capabilities a healthy talent ecosystem needs." ]), sources: officialSources },
];

const companyPages = [
  capability("about","About Softbridge","Company","About Softbridge Solutions, an Adana-based AI engineering and software company.","Softbridge Solutions is an artificial intelligence company based in Adana, Türkiye. We work at the intersection of AI systems, enterprise software, workflow design and digital transformation.",["Our purpose is to turn advances in models into dependable systems that improve real work.","We value clear problem definitions, evidence, responsible control and software that can be operated over time.","Verified legal, address and company-registration details should be added before broad public launch."]),
  capability("our-mission","Our Mission","Company direction","The mission guiding Softbridge Solutions’ AI engineering work.","Our mission is to help organizations make artificial intelligence useful, understandable and accountable in the work that matters.",["We connect emerging capability to concrete operating needs.","We design systems people can inspect, guide and improve.","We share practical knowledge that helps the wider field make better decisions."]),
  capability("our-vision","Our Vision","Company direction","The long-term vision for human-centered enterprise AI.","We envision organizations where AI expands human capacity without obscuring responsibility: systems handle repeatable complexity while people retain authority over consequential judgment.",["Models will change quickly; durable architecture must preserve choice.","Trust grows from evidence, transparency and appropriate control.","Adana can become a serious regional base for practical AI work when talent, industry needs and responsible engineering meet." ]),
  capability("leadership","Leadership","People","Leadership and expert authorship at Softbridge Solutions.","Leadership details are intentionally awaiting verification. This page is structured to provide biographies, areas of responsibility, professional history and authored work once approved.",["Named profiles should use verified titles, experience and professional links.","Every research or engineering publication should identify its accountable author.","Do not infer team members, credentials, clients or awards from incomplete information."]),
  capability("engineering","Engineering","How we build","Softbridge Solutions’ principles for engineering dependable AI systems.","We treat AI as a software and operations discipline. Models are components inside systems with data contracts, interfaces, permissions, evaluation, observability and owners.",["Prefer the smallest architecture that satisfies the evidence.","Design for model change, uncertain outputs and recoverable failure.","Make quality, cost, latency and human intervention visible in operation."]),
  capability("research","Research","Applied inquiry","Applied AI research and evaluation at Softbridge Solutions.","Our research direction centers on reliable agents, grounded generation, evaluation and the interaction between people and AI systems.",["Research claims must be supported by disclosed methods and limits.","Applied work should connect a technical question to an operating consequence.","Publications will include dates, authorship, references and revision notes when released."]),
  capability("products","Products","Software","AI products and software applications from Softbridge Solutions.","This is the future home of verified Softbridge Solutions products. Product claims, availability and pricing will be published only when confirmed.",["Each product page will define the user, problem, system behavior and important limitations.","SoftwareApplication and Product structured data will be added only for real, available offerings.","Explore current solution capabilities while the product portfolio is prepared."]),
  capability("case-studies","Case Studies","Applied work","Evidence-led case studies for enterprise AI systems.","Case studies will document the problem, constraints, method, system and measured outcome of verified work. No customer names or performance claims are presented without approval.",["Strong case studies separate starting conditions from intervention and result.","Measures should explain time period, definition and limitations.","Anonymized studies may be used when confidentiality permits and context remains useful."]),
  capability("press","Press","Newsroom","Verified announcements and media resources from Softbridge Solutions.","This newsroom will contain verified company announcements, media references and approved brand resources.",["Every release will include a publication date and contact owner.","Historical corrections and material updates should remain visible.","Press contact details are pending verification."]),
  capability("events","Events","Community","Events, technical sessions and public appearances from Softbridge Solutions.","Confirmed talks, workshops and community events will be listed here with dates, venues, speakers and access details.",["Event entries must distinguish organizer, host and participant roles.","Recordings and materials can extend the usefulness of completed events.","No upcoming events are claimed at this time."]),
  capability("careers","Careers","Join the team","Career opportunities at an Adana-based AI engineering company.","Softbridge Solutions is building an environment for careful, curious people who want to turn AI capability into dependable software. Open roles will appear here only when verified.",["Role pages should state outcomes, responsibilities, location and hiring process clearly.","We value systems thinking, evidence and direct communication.","No open positions are claimed at this time; speculative applications can use the contact page."]),
  capability("faq","Frequently Asked Questions","Reference","Answers about Softbridge Solutions, enterprise AI engagements and responsible delivery.","This page answers common questions about who Softbridge Solutions is, what we build and how we approach enterprise AI work.",["Softbridge Solutions is based in Adana, Türkiye and focuses on AI engineering, enterprise software and digital transformation.","Engagement scope begins with the workflow, constraints and evidence—not a predetermined model.","Company-specific legal and contact details will be published once verified."]),
  capability("contact","Contact","Start a conversation","Contact Softbridge Solutions about enterprise AI engineering in Adana, Türkiye.","Bring us a workflow, decision or product where AI may create measurable value. A useful first note describes the current process, users, systems and consequence of getting it wrong.",["Share the operating problem and who owns it.","Describe available data, systems and important constraints.","Verified direct email, telephone and office-address details are pending publication."]),
  capability("ai-solutions","AI Solutions","Capabilities","Explore Softbridge Solutions’ AI agents, enterprise AI, generative AI, LLM and automation capabilities.","Our capabilities connect models to enterprise context. Each area is approached as part of a complete system: data, software, workflow, evaluation and human control.",["Explore agents, enterprise AI, generative AI, language-model development and workflow automation.","Supporting capabilities include machine learning, computer vision and natural language processing.","The right architecture follows from the task, operating environment and evidence."]),
  capability("industries","Industries","Operating contexts","AI systems for financial services, healthcare, manufacturing, retail, professional services and technology.","Industry context changes what a useful and responsible AI system looks like. Language, processes, data, risk and integration patterns must be understood before design decisions are made.",["We learn the workflow and its exceptions with domain experts.","Controls are mapped to the consequences and reversibility of decisions.","Industry pages provide use cases and design considerations, not unsupported outcome claims."]),
  capability("resources","Resources","Knowledge center","Engineering articles, research papers, whitepapers, benchmarks, datasets, documentation and local AI ecosystem guides.","The Softbridge Solutions knowledge center organizes practical AI engineering content for human readers and machine retrieval. Each collection is built for clear provenance, semantic depth and future expansion.",["Content clusters connect concepts, implementations, evidence and related systems.","Pages use clear authorship, publication and revision metadata when items are available.","Explore engineering, research, technical topics, local ecosystem guides and open resources."]),
];

const industryPages:PageData[] = industries.map(x=>capability(`industries/${x.slug}`,x.title,"Industry context",`AI engineering considerations and use cases for ${x.title.toLowerCase()}.`,`AI in ${x.title.toLowerCase()} should be designed around sector language, workflows, evidence and consequences. Softbridge Solutions approaches the domain from Adana with Türkiye’s operating context in mind.`,
[
  `Potential applications include ${x.focus.toLowerCase()}. Candidate workflows require validation with domain owners before implementation.`,
  "Privacy, security, recordkeeping, human review and applicable regulation must be mapped to the specific system and jurisdiction.",
  "A first engagement should establish the workflow baseline, representative cases and measurable definition of improvement.",
]));

export const pages: PageData[] = [...primarySolutions, ...additionalSolutions, ...resourcePages, ...knowledgePages, ...localPages, ...companyPages, ...industryPages];
export const pageMap = new Map(pages.map(x=>[x.slug,x]));
