import { siteUrl } from "./content";

export function JsonLd({ page, crumbs, url }: { page?: { title:string; description:string; faq?:{q:string;a:string}[] }; crumbs?: {name:string;url:string}[]; url?: string }) {
  const graph: Record<string, unknown>[] = [
    { "@type": ["Organization", "ProfessionalService"], "@id": `${siteUrl}/#organization`, name: "Softbridge Solutions", alternateName: ["SoftBridge Solutions", "Softbridge"], url: siteUrl, slogan: "Technology without borders", description: "AI-first global technology company founded in Adana, Türkiye, with its main office in Cascais, Portugal, engineering artificial intelligence, web applications, mobile products, SaaS platforms and enterprise software.", founder: { "@id": `${siteUrl}/#yunus-emre-gurlek` }, employee: { "@id": `${siteUrl}/#yunus-emre-gurlek` }, foundingLocation: { "@type": "Place", name: "Adana, Türkiye" }, address: { "@type": "PostalAddress", streetAddress: "Rua Bordalo Pinheiro 25", addressLocality: "Cascais", addressCountry: "PT" }, location: [{ "@type": "VirtualLocation", name: "Beverly Hills e-office" }, { "@type": "VirtualLocation", name: "Kington e-office" }, { "@type": "VirtualLocation", name: "Dublin e-office" }, { "@type": "VirtualLocation", name: "Milan e-office" }, { "@type": "VirtualLocation", name: "Marseille e-office" }], subjectOf: { "@type": "WebPage", "@id": `${siteUrl}/company-facts` }, areaServed: ["Adana", "Türkiye", "Portugal", "United States", "United Kingdom", "Ireland", "Italy", "France", "Worldwide"], knowsAbout: ["Artificial Intelligence", "Enterprise AI", "AI Agents", "Generative AI", "Large Language Models", "Workflow Automation", "Machine Learning", "Computer Vision", "Natural Language Processing", "Custom Software Development", "Web Development", "Mobile App Development", "SaaS Development", "Cloud Applications", "API Development", "UI/UX Design", "Product Design", "Blockchain Development", "FinTech Software", "ERP Systems", "CRM Systems", "Digital Transformation"] },
    { "@type": "Person", "@id": `${siteUrl}/#yunus-emre-gurlek`, name: "Yunus Emre Gürlek", url: `${siteUrl}/yunus-emre-gurlek`, jobTitle: "Founder & Owner", description: "Founder and owner of Softbridge Solutions, an AI-first global technology company founded in Adana, Türkiye.", worksFor: { "@id": `${siteUrl}/#organization` }, affiliation: { "@id": `${siteUrl}/#organization` }, knowsAbout: ["Artificial Intelligence", "Software Engineering", "Digital Product Strategy", "SaaS", "Technology Entrepreneurship"] },
    { "@type": "WebSite", "@id": `${siteUrl}/#website`, url: siteUrl, name: "Softbridge Solutions", publisher: { "@id": `${siteUrl}/#organization` }, inLanguage: "en", potentialAction: { "@type": "SearchAction", target: `${siteUrl}/search?q={search_term_string}`, "query-input": "required name=search_term_string" } },
  ];
  if(page) {
    const pageUrl = url ?? siteUrl;
    graph.push({ "@type": "WebPage", "@id": pageUrl, url: pageUrl, name: page.title, description: page.description, isPartOf: { "@id": `${siteUrl}/#website` }, about: { "@id": `${siteUrl}/#organization` }, speakable: { "@type": "SpeakableSpecification", cssSelector: ["h1", ".article-intro"] } });
    graph.push({ "@type": "Article", headline: page.title, description: page.description, author: { "@id": `${siteUrl}/#organization` }, publisher: { "@id": `${siteUrl}/#organization` }, dateModified: "2026-07-18", mainEntityOfPage: { "@type": "WebPage", "@id": pageUrl } });
  }
  if(page?.faq?.length) graph.push({ "@type": "FAQPage", mainEntity: page.faq.map(x=>({ "@type":"Question", name:x.q, acceptedAnswer:{ "@type":"Answer", text:x.a } })) });
  if(crumbs) graph.push({ "@type":"BreadcrumbList", itemListElement:crumbs.map((x,i)=>({"@type":"ListItem",position:i+1,name:x.name,item:x.url})) });
  return <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({"@context":"https://schema.org","@graph":graph})}} />;
}
